apiVersion: apps/v1
kind: Deployment
metadata:
  name: managerchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managerchat
  template:
    metadata:
      labels:
        app: managerchat
    spec:
      containers:
      - name: managerchat
        image: despossivel/manager-chat:TAG
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
